{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. An exception is an event that occurs during the execution of a program that disrupts the normal flow of instructions. In Python, exceptions are objects of classes, which are the subclasses of the BaseException class. All exception classes are the subclasses of the BaseException class. However, almost all built-in exception classes inherit from the Exception class, which is the subclass of the BaseException class ¹. \n",
    "\n",
    "Q2. When an exception is not handled, it will cause the program to terminate abruptly with an error message. For example, if you try to divide a number by zero, Python will raise a ZeroDivisionError exception ². \n",
    "\n",
    "Q3. In Python, we use try-except statements to handle exceptions. The try block contains code that might raise an exception while the except block contains code that handles the exception. Here's an example:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    x = int(input(\"Please enter a number: \"))\n",
    "    y = int(input(\"Please enter another number: \"))\n",
    "    print(x / y)\n",
    "except ZeroDivisionError:\n",
    "    print(\"You cannot divide by zero!\")\n",
    "```\n",
    "\n",
    "In this example, if you try to divide a number by zero, Python will raise a ZeroDivisionError exception and the except block will handle it by printing \"You cannot divide by zero!\" ⁵.\n",
    "\n",
    "Q4. Here's an example:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"You cannot divide by zero!\")\n",
    "else:\n",
    "    print(\"The result is:\", x)\n",
    "finally:\n",
    "    print(\"This will always execute.\")\n",
    "```\n",
    "\n",
    "In this example, we try to divide 1 by 0 which raises a ZeroDivisionError exception. The except block handles this exception by printing \"You cannot divide by zero!\". Since there is no error in the try block, the else block executes and prints \"The result is: 1\". Finally, the finally block executes and prints \"This will always execute.\" ⁴.\n",
    "\n",
    "Q5. Custom exceptions are user-defined exceptions that can be raised when a certain condition occurs. We need custom exceptions when we want to raise an exception that is not already defined in Python or when we want to create our own hierarchy of exceptions. Here's an example:\n",
    "\n",
    "```python\n",
    "class MyException(Exception):\n",
    "    pass\n",
    "\n",
    "def my_function():\n",
    "    raise MyException(\"This is my custom exception.\")\n",
    "\n",
    "try:\n",
    "    my_function()\n",
    "except MyException as e:\n",
    "    print(e)\n",
    "```\n",
    "\n",
    "In this example, we define a custom exception called MyException which inherits from the built-in Exception class. We then define a function called my_function() which raises this custom exception with a message \"This is my custom exception.\" We then call this function inside a try-except block and handle the MyException exception by printing its message ⁴.\n",
    "\n",
    "Q6. Here's an example:\n",
    "\n",
    "```python\n",
    "class MyException(Exception):\n",
    "    pass\n",
    "\n",
    "class MyClass:\n",
    "    def __init__(self):\n",
    "        self._x = None\n",
    "\n",
    "    def get_x(self):\n",
    "        return self._x\n",
    "\n",
    "    def set_x(self, value):\n",
    "        if value < 0:\n",
    "            raise MyException(\"Value cannot be negative.\")\n",
    "        self._x = value\n",
    "\n",
    "try:\n",
    "    obj = MyClass()\n",
    "    obj.set_x(-1)\n",
    "except MyException as e:\n",
    "    print(e)\n",
    "```\n",
    "\n",
    "In this example, we define a custom exception called MyException which inherits from the built-in Exception class. We then define a class called MyClass which has two methods get_x() and set_x(). The set_x() method raises the MyException exception if the value passed to it is negative. We then create an object of MyClass and call its set_x() method with a negative value inside a try-except block and handle the MyException exception by printing its message ⁸.\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
